repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: 'https://github.com/psf/black-pre-commit-mirror'
    rev: 22.8.0
    hooks:
      - id: black
        language_version: python3.12
  - repo: https://github.com/PyCQA/autoflake
    rev: v1.7.6
    hooks:
      - id: autoflake
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [ "--profile", "black", "--filter-files" ]
  - repo: https://github.com/pycqa/flake8
    rev: 'b71be90ef61b346807cd724c760a3995f540abbd'
    hooks:
      - id: flake8
        args: ["--max-line-length=140", "--ignore=B006,E800,W503,E231,B010,E241"]
        additional_dependencies:
          - flake8-eradicate
          - flake8-print
          - flake8-bugbear
        language_version: python3.12
